id: D8CB93937
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:59:31+00:00'
last_modified: '2022-05-26T10:18:47.148292+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    d44f:
      image_group_id: I1PD95863
      title: དཔལ་གསང་བ་འདུས་པའི་རྫོགས་རིམ་མཐར་ཕྱིན་པ།
      total_pages: 1634
      order: 18
      base_file: d44f.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
